#! /bin/sh

name=font-misc-misc
version=1.1.3
revision=1
tarball_url="https://www.x.org/releases/individual/font/font-misc-misc-${version}.tar.xz"
tarball_blake2b="0b56e86ddcf11623a3e05da2571fec30fbc763fa1916fcbee8a2eac64fb5b1722d5a9da8f192655e88220077763121670618fee9878fa3174ea73fe6d50f6654"
hostdeps="gcc pkg-config bdftopcf mkfontscale xorg-font-util"
builddeps="xorg-font-util xorg-util-macros"

prepare() {
    autotools_recursive_regen
}

configure() {
    autotools_configure \
        --with-fontrootdir=/usr/share/fonts/X11 \
        --with-fontdir=/usr/share/fonts/X11/misc \
        --with-compression=no
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    # xorg-fonts generates one index after both bitmap font packages are in
    # its build sysroot.
    rm -f "${dest_dir}${prefix}"/share/fonts/X11/misc/fonts.dir
}
