#! /bin/sh

name=unix-socket-close
skip_pkg_check=yes
version=1.0
revision=1
source_dir="tests/unix-socket-close"
hostdeps="gcc"
deps="core-libs"

build() {
    cp -rp "${source_dir}"/. ./

    ${OS_TRIPLET}-gcc \
        $TARGET_CFLAGS \
        $TARGET_CPPFLAGS \
        main.c \
        $TARGET_LDFLAGS \
        -o unix-socket-close
}

package() {
    install -d "${dest_dir}${prefix}"/bin
    install -m 0755 unix-socket-close "${dest_dir}${prefix}"/bin/

    post_package_strip
}
