#! /bin/sh

# Complete Vinix X environment. Keep this as a meta-package so the X server
# and its loadable drivers retain their correct one-way build dependencies.
name=xorg
skip_pkg_check=yes
version=0.0
revision=1
deps="xorg-server xorg-xinit xorg-fonts xf86-video-fbdev xf86-input-keyboard xf86-input-mouse"
