timeout: 0
verbose: yes

/Vinix
    protocol: limine
    kernel_path: boot():/boot/vinix
    cmdline: root=PARTUUID=7c1b4f10-8e2d-4d6a-9f35-6ab472008103 rootfstype=ext2 ro
    resolution: 1024x768x32
    kaslr: no
